version: '3'

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          memory: 100M
  web:
    container_name: web
    build:
      context: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 100M
    env_file:
      - local-var.env
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links: 
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
  celery:
    container_name: celery
    build: .
    command: celery worker -A app -l info
    deploy:
      resources:
        limits:
          memory: 50M
    volumes:
      - ./app:/app
    links:
      - db
      - redis
  celery-beat:
    container_name: celery-beat
    build: .
    command: celery beat -A app -l info
    deploy:
      resources:
        limits:
          memory: 50M
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis

  deploy_staging:
    build: .
    env_file:
      - deploy-staging-var.env

  deploy_production:
    build: .
    env_file:
      - deploy-production-var.env
      
volumes:
    postgres_data: