version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - local-var.env
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links: 
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
  celery:
    build: .
    command: celery -A app.tasks worker -B
    volumes:
      - .:/code
    links:
      - db
      - redis

  deploy_staging:
    build: .
    env_file:
      - deploy-staging-var.env

  deploy_production:
    build: .
    env_file:
      - deploy-production-var.env
      
volumes:
    postgres_data: