"""
    Copyright 2020-2021 Paloma Piot Pérez-Abadín
	
	This file is part of early.
    early is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    early is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with early.  If not, see <https://www.gnu.org/licenses/>.
"""

version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - local-var.env
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links: 
      - db
      - redis
  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  celery:
    container_name: celery
    build: .
    command: celery worker -A app -l info
    volumes:
      - ./app:/app
    links:
      - web
      - db
      - redis
    depends_on: 
      - redis

  deploy_staging:
    build: .
    env_file:
      - deploy-staging-var.env

  deploy_production:
    build: .
    env_file:
      - deploy-production-var.env
      
volumes:
    postgres_data: