version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - local-var.env
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links: 
      - db
      - redis
    networks:
      - "backend"

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    networks:
      - "backend"

  celery:
    container_name: celery
    build: .
    command: celery worker -A app -l info
    volumes:
      - ./app:/app
    links:
      - web
      - db
      - redis
    depends_on: 
      - redis

  deploy_staging:
    build: .
    env_file:
      - deploy-staging-var.env

  deploy_production:
    build: .
    env_file:
      - deploy-production-var.env
      
volumes:
    postgres_data:

networks:
  backend: